# Generated by Django 5.1.1 on 2025-07-16 18:48

import users.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=9, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательно. Не более 150 символов. Только буквы, цифры и @/./+/-/_. ', max_length=150, unique=True, validators=[users.services.validate_username_value], verbose_name='никнейм'),
        ),
    ]
